############################
#                          #
#      CONFIGURATION       #
#                          #
############################

#################
#    General    #
#################

homeassistant:
  name: Home

##################################
#    Master bed room             #
##################################

clothesCloset:
  rangaClothes:
    - hangers
    - t-shirts
    - shorts
    - pants
    - underwears
  ironbox:
bed:
  - beddingBox
  -
bookShelf:
  Akshu:
    - SchoolLibrary
    - Reading books
    - Public Library
  Ranga:
    - Public Library
    - Own Books
  Decorables

windowSill:
  - Empty
bathroomShelf:




system_health:

lovelace:
  mode: yaml

dialogflow:
# ifttt:
#   key: !secret iftttkey
logbook:
map:

python_script:
shopping_list:
sun:
updater:

#################
#    Include    #
#################

alarm_control_panel: !include config_files/alarm.yaml
# android_ip_webcam: !include misc/android_ip_webcam.yaml
automation: !include config_files/automation.yaml
binary_sensor: !include config_files/binary_sensor.yaml
camera: !include config_files/camera.yaml
cast: !include config_files/cast.yaml
# cloud: !include config_files/cloud.yaml
climate: !include config_files/climate.yaml
device_tracker: !include config_files/device_tracker.yaml
frontend: !include config_files/frontend.yaml
# google_assistant: !include config_files/google_assistant.yaml
# googlehome: !include config_files/googlehome.yaml
group: !include config_files/group.yaml
history: !include config_files/history.yaml
# homeconnect: include !config_files/home_connect.yaml
homekit: !include config_files/homekit.yaml
# http: !include config_files/http.yaml
hue: !include config_files/hue.yaml
# influxdb: !include config_files/influxdb.yaml
input_boolean: !include config_files/input_boolean.yaml
input_select: !include config_files/input_select.yaml
input_number: !include config_files/input_number.yaml
# intent_script: !include config_files/intent_script.yaml
ios: !include config_files/ios.yaml
joaoapps_join: !include config_files/joaoapps_join.yaml
light: !include config_files/light.yaml
logger: !include config_files/logger.yaml
media_player: !include_dir_merge_list config_files/media_player/
mqtt: !include config_files/mqtt.yaml
notify: !include config_files/notify.yaml
owntracks: !include config_files/owntracks.yaml
# packages: !include config_files/packages.yaml
panel_custom: !include config_files/panel_custom.yaml
panel_iframe: !include config_files/panel_iframe.yaml
plant: !include config_files/plant.yaml
recorder: !include config_files/recorder.yaml
remote: !include config_files/remote.yaml
# roku: !include config_files/roku.yaml
scene: !include_dir_merge_list config_files/scene/
script: !include_dir_merge_named config_files/script/
sensor: !include_dir_merge_list config_files/sensor/
shell_command: !include config_files/shell_commands.yaml
skybell: !include config_files/skybell.yaml
#snips: !include config_files/snips.yaml
sonos: !include config_files/sonos.yaml
switch: !include config_files/switch.yaml
telegram_bot: !include config_files/telegram_bot.yaml
tts: !include config_files/tts.yaml
weblink: !include config_files/weblink.yaml
wemo: !include config_files/wemo.yaml
yeelight: !include config_files/yeelight.yaml
zone: !include config_files/zone.yaml
zwave: !include config_files/zwave.yaml
xiaomi_aqara: !include config_files/xiaomi_aqara.yaml